[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
libc = "0.2.164"
nix = { version = "0.25.1", features = ["term"] }
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = "0.7.12"
